version: "3.9"

services:

  database:
    container_name: "doctorinna-risks-db"
    image: postgres:13.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database-risks:/var/lib/postgresql/data
    networks:
      - database_network

  rabbitmq:
    container_name: "doctorinna-risks-broker"
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    depends_on:
      - database
    networks:
      - database_network
      - nginx_network

  django_gunicorn:
    container_name: "doctorinna-gunicorn"
    image: "aldanis/doctorinna-api:latest"
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - database_network
      - nginx_network

  nginx:
    container_name: "doctorinna-nginx"
    image: "aldanis/doctorinna-nginx:latest"
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - nginx_network
    links:
      - rabbitmq

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database-risks:
  static: