version: "3.9"

services:

  database:
    container_name: "doctorinna-risks-db"
    image: postgres:13.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database-risks:/var/lib/postgresql/data

  django_gunicorn:
    image: "aldanis/doctorinna-api:stable"
    scale: 3
    volumes:
      - static:/static
    env_file:
      - .env
    depends_on:
      - database

  nginx:
    container_name: "doctorinna-nginx"
    image: "ladamoroz/doctorinna-nginx:balance_latest"
    volumes:
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn


volumes:
  database-risks:
  static:
