---

- name: Pull NGINX image and run container
  docker_container:
    name: "{{ NGINX_CONTAINER }}"
    image: "{{ REGISTRY }}/{{ NGINX_IMAGE }}"
    pull: yes
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static