---

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes
  
- name: Add APT key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add APT repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user permissions
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker

- name: Install Python3
  apt:
    name: python3
    
- name: Install PIP
  apt:
    name: python3-pip

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3

- name: Install Docker SDK for Python
  pip:
    name:
      - docker
    executable: pip3

- name: Log into DockerHub
  docker_login:
    username: "{{ REGISTRY_USER }}"
    password: "{{ REGISTRY_PASSWORD}}"