name: CI dev

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8 pytest
          flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run ./backend/manage.py test
          coverage report
      - name: Run tests
        run: |
          python ./backend/manage.py test